/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangchao_audioandvideo_task_task_ffmpeg_Task_FFmpegActivity */

#ifndef _Included_com_zhangchao_audioandvideo_task_task_ffmpeg_Task_FFmpegActivity
#define _Included_com_zhangchao_audioandvideo_task_task_ffmpeg_Task_FFmpegActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangchao_audioandvideo_task_task_ffmpeg_Task_FFmpegActivity
 * Method:    native_initFFmpeg
 * Signature: ()V
 */
JNIEXPORT void JNICALL sJava_com_zhangchao_audioandvideo_task_task_1ffmpeg_Task_1FFmpegActivity_native_1initFFmpeg
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangchao_audioandvideo_task_task_ffmpeg_Task_FFmpegActivity
 * Method:    native_setMediaPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL sJava_com_zhangchao_audioandvideo_task_task_1ffmpeg_Task_1FFmpegActivity_native_1setMediaPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zhangchao_audioandvideo_task_task_ffmpeg_Task_FFmpegActivity
 * Method:    native_setCallback
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL sJava_com_zhangchao_audioandvideo_task_task_1ffmpeg_Task_1FFmpegActivity_native_1setCallback
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
